<?php $model = Mage::getModel('clickdesk/clickdesk'); ?>
<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?= $this->__('Clickdesk') ?></h3></td>
            <td class="a-right">
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Save Widget Id</span></button>
            </td>
        </tr>
    </table>
</div>

<div class="entry-edit">
    <?php
    $iframeurl = $model->getWidgetCurl() . urlencode($this->getUrl('*/*/index') . "?g=1");
    if (strlen($model->getWidgetId()) != 0) {
        $mssg = urlencode("Plugin has been installed successfully.");
        $iframeurl = $iframeurl . "&mssg=" . $mssg;
    }
    ?>
    <form id="edit_form" name="edit_form" method="post" action="<?= $this->getUrl('*/*/post') ?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?= $this->__('Widget Id') ?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?= $this->__('Widget Id') ?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text " value="<?php echo $model->getWidgetId(); ?>" name="clickdesk[widgetid]" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
    <iframe width="100%" border="0" height="1200px" src="<?php echo $iframeurl ?>" scrolling="yes"></iframe>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>