<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <mageworkshophq@gmail.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */

$_items = $this->getReviewsCollection()->getItems();
$isCustomerLogged = $this->helper('customer')->isLoggedIn();
$customerId = $isCustomerLogged ? $this->helper('customer')->getCustomer()->getId() : null;
$isGuestAllowToWrite = $this->helper('review')->getIsGuestAllowToWrite();
$isGuestAllowToVote = Mage::getStoreConfig('detailedreview/settings_customer/allow_guest_vote');
$show_vb_image = Mage::getStoreConfig('detailedreview/settings_customer/show_verified_buyer_image');

if (!$isCustomerLogged){
    $helperUrl = $this->helper('core/url');
    $url = $this->getUrl('detailedreview/helpful/vote', array('_secure' => Mage::app()->getStore()->isCurrentlySecure()));
}
$helperDetailedreview = $this->helper('detailedreview');
if (!$dateFormat = Mage::getStoreConfig('detailedreview/datetime_options/date_format')) {
    $dateFormat = 'dd/MM/YY';
}
if (!$timeFormat = Mage::getStoreConfig('detailedreview/datetime_options/time_format')) {
    $timeFormat = 'hh:mm ' . Zend_Date::MERIDIEM;
}
$enableClientTimezone = Mage::getStoreConfig('detailedreview/datetime_options/enable_to_set_timezone');
//$_product = Mage::app()->getLayout()->getBlock('product.info')->getProduct();
$_product = Mage::registry('product');
?>
<?php if (count($_items)): ?>
    <div class="box-collateral box-reviews" id="customer-reviews">
        <?php echo $this->getChildHtml('toolbar') ?>
        <?php $reviewSizing = Mage::getSingleton('detailedreview/review_sizing'); ?>
        <?php $reviewBodyType = Mage::getSingleton('detailedreview/review_bodyType'); ?>
        <?php /** @var $_review MageWorkshop_DetailedReview_Model_Review */?>
        <?php foreach ($_items as $keyReview => $_review):?>
            <div itemprop="review" itemscope itemtype="http://schema.org/Review">
                <div class="review-hr"></div>
                <div class="review-dt" id="<?php echo 'rw_'.$_review->getId(); ?>">
                    <span itemprop="author" class="nickname"><?php echo $this->escapeHtml($_review->getNickname()); ?></span>
                    <?php if ($_review->getCustomerId()): ?>
                        <span class="review-img customer-image" title="<?php echo $this->__('Customer'); ?>"></span>
                    <?php else: ?>
                        <span class="review-img guest-image" title="<?php echo $this->__('Guest'); ?>"></span>
                    <?php endif; ?>
                    <?php $ownership = $_review->getOwnership(); ?>
                    <?php if ($show_vb_image && $ownership):?>
                        <span class="review-img vb-image" title="<?php echo $this->__('Verified Buyer'); ?>"></span>
                    <?php endif; ?>
                    <?php $date = new Zend_Date($_review->getCreatedAt()); ?>
                    <small itemprop="datePublished" class="date review-date" data-utc="<?php echo $_review->getCreatedAt(); ?>" data-format="<?php echo $dateFormat; ?>"><?php echo $date->get($dateFormat) ?></small>
                    <small class="date review-date" data-utc="<?php echo $_review->getCreatedAt(); ?>" data-format="<?php echo $timeFormat; ?>"><?php echo $date->get($timeFormat); ?></small>
                    <?php $isAllowAboutYou = $helperDetailedreview->checkFieldAvailable('about_you', 'form'); ?>
                    <?php if ( $isAllowAboutYou || $ownership ): ?>
                        <ul class="<?php echo ($bodyType = $_review->getBodyType()) ? 'body-type' : ''; ?>">
                        <?php if ( $isAllowAboutYou ): ?>
                            <?php if ($location = $_review->getLocation()): ?>
                                <li>
                                    <label class="label-review-attr"><?php echo $this->__('Location') ?>:</label>
                                    <div class="value-review-attr"><?php echo $this->escapeHtml($location); ?></div>
                                </li>
                            <?php endif;?>
                            <?php if ($age = $_review->getAge()): ?>
                                <li><label class="label-review-attr left"><?php echo $this->__('Age') ?>:&nbsp;</label><div class="value-review-attr left"><?php echo $this->escapeHtml($age); ?></div></li>
                            <?php endif;?>
                            <?php if ( $height = $_review->getHeight() ):?>
                                <li><label class="label-review-attr left"><?php echo $this->__('Height') ?>:&nbsp;</label><div class="value-review-attr left"><?php echo $this->escapeHtml($height); ?></div></li>
                            <?php endif;?>
                            <?php if ( $bodyType = $_review->getBodyType() ):?>
                                <li><label class="label-review-attr body"><?php echo $this->__('Body Type') ?>:</label><div class="value-review-attr body"><img class="body-type" alt="" src="<?php echo $this->helper('detailedreview')->getResizedImage( $this->getSkinUrl('images/detailedreview/bodytypes/'.$reviewBodyType->getOptionValue($bodyType).'-shape.png' ),null,70); ?>"/></div></li>
                            <?php endif;?>
                        <?php endif;?>
                        <?php if ($ownership):?>
                            <li><label class="label-review-attr"><?php echo $this->__('Ownership') ?>:</label><div class="value-review-attr ownership"><?php echo $this->escapeHtml($ownership); ?></div></li>
                        <?php endif;?>
                    </ul>
                    <?php endif;?>
                </div>
                <div class="header-reviews">
                    <?php $_votes = $_review->getRatingVotes(); ?>
                    <?php if ($countVotes = count($_votes)): ?>
                        <ul class="ratings-table">
                            <?php foreach ($_votes as $_vote): ?>
                                <li>
                                    <?php if ($countVotes > 1): ?>
                                        <span><?php echo $this->__($_vote->getRatingCode() . ':'); ?></span>
                                    <?php endif; ?>
                                    <div class="rating-box">
                                        <div class="rating" style="width:<?php echo $_vote->getPercent(); ?>%;">
                                            <div itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                                <meta itemprop="worstRating" content="1" />
                                                <meta itemprop="ratingValue" content="<?php echo $_vote->getPercent(); ?>" />
                                                <meta itemprop="bestRating" content="100" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="clearboth"></div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <?php if ( ( $helperDetailedreview->checkFieldAvailable('sizing', 'form') ) && ($sizing = $_review->getSizing()) ):?>
                        <div class="sizing">
                            <label class="label-review-attr sizing"><?php echo $this->__('Sizing') ?>:</label>
                            <div class="review-sizing">
                                <div class="sizing-bar separate">
                                    <div style="width:<?php echo $reviewSizing->getOptionWidth($sizing) ?>%;"></div>
                                </div>
                                <div class="sizing-value"><?php echo $reviewSizing->getOptionValue($sizing) ?></div>
                            </div>
                            <div class="clearboth"></div>
                        </div>
                    <?php endif;?>
                    <?php if(Mage::getStoreConfig('detailedreview/social_share_optios/recommended_product') && $_review->getRecommendTo()): ?>
                        <div class="recommend">
                            <span><?php echo $this->__('Recommend: '); ?></span>
                            <div class="recommend-title">
                                <div class="recommend-value">
                                    <?php echo $this->escapeHtml($_review->getRecommendTo()); ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="review-dd">
                   <div class="top-review">
                        <div class="images-box">
                            <?php if ( $helperDetailedreview->checkFieldAvailable('image', 'form') ):
                                $images = explode(",",$_review->getImage());
                                foreach($images as $img):
                                    if ( isset($newImageUrl) ) unset ($newImageUrl);
                                    if ( $image = str_replace('\\','/',$img) ) {
                                        $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . $image;
                                        $newImageUrl = $this->helper('detailedreview')->getResizedImage($image,100,100);
                                    }
                                    if ( isset($newImageUrl) && $newImageUrl ): ?>
                                        <div class="image-review">
                                            <a class="image-popup" href="<?php echo  $image;?>" >
                                                <img src="<?php echo $newImageUrl;?>" alt=""/>
                                            </a>
                                            <div><?php $this->__('click for full-size image'); ?></div>
                                        </div>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </div>
                        <div class="clearboth"></div>
                        <div class="title"><?php echo nl2br($_review->getTitle()); ?></div>
                        <?php if ( $detail = $_review->getDetail() ):?>
                            <div itemprop="description" class="value-review-attr description"><?php echo nl2br($this->escapeHtml($detail)) ?></div>
                        <?php endif;?>
                   </div>

                    <div class="review-wrapper">
                        <ul>
                            <?php if ( $helperDetailedreview->checkFieldAvailable('good_and_bad_detail', 'form') ): ?>
                                <?php if ( $goodDetail = $_review->getGoodDetail() ): ?>
                                    <li><label class="label-review-attr"><?php echo $this->__('What do you like about this item?') ?>:</label><div class="value-review-attr"><?php echo nl2br($this->escapeHtml($goodDetail)) ?></div></li>
                                <?php endif;?>
                                <?php if ( $noGoodDetail = $_review->getNoGoodDetail() ):?>
                                    <li><label class="label-review-attr"><?php echo $this->__('What do you dislike about this item?') ?>:</label><div class="value-review-attr"><?php echo nl2br($this->escapeHtml($noGoodDetail)) ?></div></li>
                                <?php endif;?>
                            <?php endif;?>

                            <?php if ( $helperDetailedreview->checkFieldAvailable('pros_and_cons', 'form') ): ?>
                                <?php if ( $goodDetail = $helperDetailedreview->getProsConsText($_review->getPros(), MageWorkshop_DetailedReview_Model_Source_EntityType::PROS) ):?>
                                    <li><label class="label-review-attr"><?php echo $this->__('Pros') ?>:</label><div class="value-review-attr"><?php echo nl2br($this->escapeHtml($goodDetail)) ?></div></li>
                                <?php endif;?>
                                <?php if ( $noGoodDetail = $helperDetailedreview->getProsConsText($_review->getCons(), MageWorkshop_DetailedReview_Model_Source_EntityType::CONS) ):?>
                                    <li><label class="label-review-attr"><?php echo $this->__('Cons') ?>:</label><div class="value-review-attr"><?php echo nl2br($this->escapeHtml($noGoodDetail)) ?></div></li>
                                <?php endif;?>
                            <?php endif;?>

                            <?php if(Mage::getStoreConfigFlag(MageWorkshop_DetailedReview_Block_Product_View_List::XML_PATH_ALLOW_VIDEO_PREVIEW) && $videoHtml = $helperDetailedreview->getVideoIFrame($_review->getVideo())): ?>
                                <li class="iframe-video">
                                    <?php echo $videoHtml; ?>
                                </li>
                            <?php endif; ?>

                            <?php if ( $helperDetailedreview->checkFieldAvailable('video', 'form') && ($videoUrl = $_review->getVideo()) ):?>
                                <li>
                                    <a class="video-review" target="_blank" href="<?php echo $this->escapeHtml($videoUrl); ?>"><?php echo $this->__('Watch my video')?></a>
                                </li>
                            <?php endif; ?>
                        </ul>
                    </div>
                    <div class="clearer"></div>

                    <div class="helpful-block">
                        <form class="helpful-form" action="<?php echo $this->getUrl('detailedreview/helpful/vote', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>" method="post" >
                            <div class="js-helpful-voting">
                                <input type="hidden" name="review_id" value="<?php echo $_review->getId()?>"/>
                                <?php $isCustomerVoted = $_review->getIsCustomerVoted(); ?>
                                <?php $isGuestVoted = $_review->checkGuestIsVoted(); ?>
                                <?php $isCustomerOwner = !is_null($customerId) && $customerId == $_review->getCustomerId(); ?>
                                <div class="rating-wrapper">
                                    <a class="review-vote-rating helpful-btn"  title="<?php echo $this->__('Helpful')?>" href="#" onclick="return false;">
                                        <span></span>
                                    </a>
                                    <span class="helpful-qty voting-qty"><?php echo $_review->getCountHelpful() ?></span>
                                </div>
                                <div class="rating-wrapper">
                                    <a class="review-vote-rating unhelpful-btn" title="<?php echo $this->__('Unhelpful')?>" href="#" onclick="return false;">
                                        <span></span>
                                    </a>
                                    <span class="unhelpful-qty voting-qty"><?php echo $_review->getCountUnhelpful() ?></span>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="social-share">
                        <?php $shareUrl = $_product->getProductUrl() . '#rw_'.$_review->getId(); ?>
                        <?php if(Mage::getStoreConfig('detailedreview/social_share_optios/share_review_to_facebook')): ?>
                            <?php $image = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'catalog/product' . $_product->getSmallImage()?>
                            <div class="share-fb">
                                <a href="javascript:fbShare('<?php echo urlencode($shareUrl); ?>', '<?php echo urlencode($_product->getName()); ?>', '<?php echo urlencode($_review->getDetail()); ?>', '<?php echo urlencode($image); ?>', 700, 400)"
                                   data-url="<?php echo $shareUrl; ?>"
                                   data-title="<?php echo urlencode($_product->getName()); ?>"
                                   data-text="<?php echo urlencode($_review->getDetail()); ?>"
                                   data-img="<?php echo urlencode($image); ?>"
                                   data-social-type="facebook"
                                   data-action="<?php echo Mage::getUrl('detailedreview/product/getShortLink', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>">
                                        <img src="<?php echo $this->getSkinUrl('images/detailedreview/fb.png');''?>" alt="Facebook" title="Facebook" width="22" height="22" />
                                </a>
                            </div>
                        <?php endif; ?>

                        <?php if(Mage::getStoreConfig('detailedreview/social_share_optios/twitt_review')): ?>
                            <div class="share-twitter">
                                <a href="<?php echo htmlspecialchars('https://twitter.com/share?dtn=true&count=none&lang=en&via=DetailedReview&text=')?><?php echo urlencode($helperDetailedreview->smartyModifierTruncate($_product->getName(), 30)); ?><?php echo htmlspecialchars('&url=')?><?php echo urlencode($shareUrl); ?>"
                                    target="_blank" class="twitter-share-button"
                                    data-url="<?php echo $shareUrl; ?>"
                                    data-text="<?php echo urlencode($helperDetailedreview->smartyModifierTruncate($_product->getName(), 30)); ?>"
                                    data-via="DetailedReview"
                                    data-social-type="twitter"
                                    data-action="<?php echo Mage::getUrl('detailedreview/product/getShortLink', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>">
                                        <img src="<?php echo $this->getSkinUrl('images/detailedreview/twitter.png');''?>" alt="Twitter" title="Twitter" width="22" height="22" />
                                </a>
                            </div>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if ( $helperDetailedreview->checkFieldAvailable('response', 'info') && ($response = $_review->getResponse()) ):?>
                    <div class="admin-response">
                        <span class="r-arrow"></span>
                        <label class="label-review-attr"><?php echo $this->__('Administration Response') ?>:</label>
                        <div class="value-review-attr"><?php echo nl2br($this->escapeHtml($response)) ?></div>
                    </div>
                <?php endif;?>
            </div>
            <div class="clearboth"></div>
        <?php endforeach; ?>
        <?php echo $this->getChildHtml('toolbar') ?>
    </div>
<?php else: ?>
        <?php if ($this->getReviewsCountWithoutFilters()): ?>
            <?php echo $this->getMessagesBlock()->addNotice($this->__('Sorry, no reviews matched your criteria.'))->_toHtml(); ?>
        <?php endif; ?>
<?php endif; ?>
    <?php if ($isGuestAllowToWrite || $isCustomerLogged): ?>
        <?php echo $this->getChildHtml('review_form') ?>
    <?php endif;?>
    <div class="clearer"></div>
<script type="text/javascript">
    //<![CDATA[
    document.observe("dom:loaded", function() {
        'use strict';
        ;(function($){
            var query = window.location.search;
            if(query != 'undefined') {
                if (query.search('feedback=1') != -1) {
                    var lis = $(".toggle-tabs").children("li");
                    $(lis).each(function(){
                        if ($(this).children('span').text() == "Reviews") {
                            $(this).trigger("click");
                        }
                    });
                }
            }
        })(DRjQuery);
        var event = document.createEvent("CustomEvent");
        event.initEvent("updateDateDR", false, true);
        window.dispatchEvent(event);
    });
    //]]>
</script>
