<?php
$_block = $this;
/* @var $_block Shopbedding_Set_Block_Tab_Images */
?>
<div>
  <div class="entry-edit-head">
    <h4 class="icon-head head-edit-form fieldset-legend">
      <?php echo $this->__('Images') ?>
    </h4>
  </div>
  <div class="fieldset">
    <div class="hor-scroll">
      <table cellspacing="0" class="form-list" style="width:100%">
        <tbody>
          <tr>
            <td>
              <div id="<?php echo $_block->getHtmlId() ?>" >
                <div class="grid">
                  <table cellspacing="0" class="data border" id="<?php echo $_block->getHtmlId() ?>_grid" width="100%">
                    <col width="120" />
                    <col />
                    <col width="100" />
                    <col width="70" />
                    <col width="70" />
                    <col width="70" />
                    <thead>
                      <tr class="headings">
                        <th><?php echo $this->__('Image') ?></th>
                        <th><?php echo $this->__('Label') ?></th>
                        <th><?php echo $this->__('Sort Order') ?></th>
                        <th><?php echo $this->__('Listing') ?></th>
                        <th><?php echo $this->__('Carousel') ?></th>
                        <th class="last"><?php echo $this->__('Remove') ?></th>
                      </tr>
                    </thead>
                    <tbody id="<?php echo $_block->getHtmlId() ?>_list">
                      <tr id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display">
                        <td class="cell-image">
                          <div class="place-holder" onmouseover="<?php echo $_block->getJsObjectName(); ?>.loadImage('__file__')">
                            <span><?php echo Mage::helper('catalog')->__('Roll Over for preview') ?></span>
                          </div>
                          <img src="<?php echo $this->getSkinUrl('images/spacer.gif')?>" width="100" style="display:none;" alt="" />
                        </td>
                        <td class="cell-label">
                          <input type="text" class="input-text" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        </td>
                        <td class="cell-sort_order">
                          <input type="text" class="input-text validate-number" onkeyup="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" onchange="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        </td>
                        <td class="cell-listing">
                          <input type="radio" name="listing" class="input-text" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        </td>
                        <td class="cell-slide">
                          <input type="radio" name="slide" class="input-text" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        </td>
                        <td class="cell-remove a-center last">
                          <input type="checkbox" onclick="<?php echo $_block->getJsObjectName(); ?>.updateImage('__file__')" />
                        </td>
                      </tr>

                      <tr id="<?php echo $_block->getHtmlId() ?>-image-0">
                        <td class="cell-image"><?php echo $this->__('No image') ?></td>
                        <td class="cell-label"><!--  --></td>
                        <td class="cell-sort_order"><!--  --></td>
                        <td class="cell-listing"><!--  --></td>
                        <td class="cell-slide"><!--  --></td>
                        <td class="cell-remove last"><!--  --></td>
                      </tr>
                    </tbody>
                    <tfoot>
                      <tr>
                        <td colspan="100" class="last" style="padding:8px">
                            <?php echo $_block->getUploaderHtml() ?>
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              </div>
              <input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="set[images]" value='<?php echo $_block->getImagesJson() ?>' />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>
<script type="text/javascript">
//<![CDATA[
var <?php echo $_block->getJsObjectName(); ?> = new Shopbedding.Gallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getUploader()->getJsObjectName() ?>, {});
//]]>
</script>