<?php
$helper = Mage::helper('newsletteroptin');
if (Mage::helper('newsletteroptin')->isEnabled()): ?>
<?php $checkbox =  ($helper->isChecked())?' checked="checked"':''?>
<li id="register-customer-newsletter" class="control"><input type="checkbox" <?php echo $checkbox; ?> name="billing[is_subscribed]" value="1" title="<?php echo Mage::helper('customer')->__('YES, I would like to receive special offers and promotions via email.') ?>" id="billing:is_subscribed" /> <label for="billing:is_subscribed"><?php echo Mage::helper('customer')->__('YES, I would like to receive special offers and promotions via email.') ?></label></li>
<script type="text/javascript">
//<![CDATA[
Element.show('register-customer-newsletter');
hideCheckoutNewsletter = function (){
	if (typeof(checkout) != 'undefined'){
    	if (checkout.method == 'register'){
    		<?php if (!$helper->isVisibleRegister()): ?>
    		Element.hide('register-customer-newsletter');
    		$('billing:is_subscribed').checked = false;
    		<?php else: ?>
    		Element.show('register-customer-newsletter');
    		<?php if ($helper->isChecked()): ?>
    		$('billing:is_subscribed').checked = true;
    		<?php endif ?>
    		<?php endif ?>
    	}
    	else if (checkout.method == 'guest'){
    		<?php if (!$helper->isVisibleGuest()): ?>
    		Element.hide('register-customer-newsletter');
    		$('billing:is_subscribed').checked = false;
    		<?php else: ?>
    		Element.show('register-customer-newsletter');
    		<?php if ($helper->isChecked()): ?>
    		$('billing:is_subscribed').checked = true;
    		<?php endif ?>
    		<?php endif ?>
    	}
	}
}
hideCheckoutNewsletter();
//setInterval("hideCheckoutNewsletter()", 100);
//]]>
</script>
<?php endif ?>