
<?php $_filters = $this->getActiveFilters() ?>
<?php $_removeTxt = Mage::helper('catalog')->__('Remove This Item') ?>
<?php $filteredList = $this->getLayout()
        ->getBlockSingleton('catalog/product_list')
        ->getLoadedProductCollection(); ?>
		
<?php $_helper = $this->helper('catalog/output');?>
<?php $_category_detail=Mage::registry('current_category');?>

<?php if (!empty($_filters)): ?>
   
   
    <div class="currently filters">
	<div class="filter-count-wrapper filter-item">
	<span class="current-category color-red"><?php echo '"'. $_category_detail->getName() .'"'; ?> </span>
	<span> we found </span>
	<span class="filter-count color-red"><?php echo count($filteredList); ?></span>
	<span> items</span>
	</div>
	<div class="itm-heading">Your Selections: </div>
    <?php foreach ($_filters as $_filter): ?>
       
            <!--span class="label"><?php echo Mage::helper('catalog')->__($_filter->getName()) ?>:</span-->
            <?php if ($_filter->hasData('children')): ?>
                <?php foreach ($_filter->getData('children') as $child): ?>
				 <div class="filter-item">
                    
                    <a href="<?php echo $child['url'] ?>" class="btn-remove-inline">
                        <?php echo $child['label'] ?><img src="<?php echo Mage::getDesign()->getSkinUrl('images/close-icon.jpg') ?>" width="11" height="11" alt="<?php echo $_removeTxt ?>" />
                    </a>
				</div>
                <?php endforeach ?>
            <?php else: ?>
			<div class="filter-item">
			
                <a href="<?php echo $_filter->getRemoveUrl() ?>" class="btn-remove-inline"> <?php echo $_filter->getLabel() ?> <img src="<?php echo Mage::getDesign()->getSkinUrl('images/close-icon.jpg') ?>" width="11" height="11" alt="<?php echo $_removeTxt ?>" /></a>
			</div>
            <?php endif ?>
       
    <?php endforeach; ?>
	<div style="clear:both"></div>  
    </div>
    <?php if (Mage::helper('amshopby')->isVersionLessThan(1, 7)): ?>
    <div class="actions"><a href="<?php echo Mage::helper('amshopby/url')->getFullUrl(array(), 1) ?>"><?php echo Mage::helper('catalog')->__('Clear All') ?></a></div>
    <?php endif; ?>
<?php endif; ?>