<?php

$_product = $this->getProduct(); 

?>


                            <?php if ($this->hasOptions()):?>
                                <?php if ($_product->isSaleable() && $this->hasOptions() && $this->getChildHtml('product_options_wrapper') ):?>
                                    <div class="options-container-small">
                                        <?php // echo $this->getChildChildHtml('container1', '', true, true) ?>
                                        <?php echo $this->getChildHtml('product_options_wrapper', '', true, true) ?>
                                    </div>
                                <?php endif;?>
                                <?php if ( false && $_product->isSaleable() && $this->hasOptions() && $this->getChildHtml('product_options_wrapper_bottom') ):?>
                                <div class="options-container-big">
                                    <?php // echo $this->getChildChildHtml('container2', '', true, true) ?>
                                    <?php echo $this->getChildHtml('product_options_wrapper_bottom', '', true, true) ?>
                                </div>
                                <?php endif;?>
                            <?php endif; ?>


