<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <mageworkshophq@gmail.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */

 ?>
<script type="text/javascript">
    //<![CDATA[
    var drConfig = <?php echo Mage::getModel('detailedreview/review_jsConfig')->getJsonConfig(); ?>;
    document.observe("dom:loaded", function() {
        DRjQuery('#feedback').detailedReview(drConfig);
        drReviewLoader = DRjQuery().ajaxLoad({
            ajaxErrorMessage: "<?php echo Mage::helper('detailedreview')->__('Unable to load review list. Please, contact support is this issue remains.'); ?>",
            url: "<?php echo Mage::getUrl('detailedreview/product/getReviewsByAjax', array('_secure' => Mage::app()->getStore()->isCurrentlySecure())); ?>",
            clearFiltersArray: <?php echo json_encode(MageWorkshop_DetailedReview_Model_Source_Sorting::getAvailableFilters()); ?>,
            queryParams: {
                product_id: <?php echo Mage::registry('current_product')->getId(); ?>
            }
        });
        DRjQuery(document).find('#review-list-crawling').hide();
        DRjQuery().drResponse();
    });
    //]]>
</script>
