<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <mageworkshophq@gmail.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */
?>
<div style="clear: both"></div>
<?php $isInTab = Mage::getStoreConfig('detailedreview/settings/reviews_in_tab') ? ' in-tab' : ''; ?>
<div class="reviews-wrapper<?php echo $isInTab; ?>">
    <?php if (!$isCustomerLogged): ?>
        <div class="login-dialog-block" style="display: none;">
            <div class="login-dialog-container">
                <?php echo $this->getChildHtml('customer_form_login');?>
                <?php echo $this->getChildHtml('customer_form_register');?>
            </div>
            <div class="clearer"></div>
        </div>
    <?php endif;?>

    <?php echo $this->getChildHtml('review_form'); ?>

    <div class="reviews-container" id="feedback">
        <div itemscope itemtype="http://schema.org/Product">
            <meta itemprop="name" content="<?php echo Mage::registry('current_product')->getName();?>" />
                <?php echo $this->getChildHtml('review-wrapper') ?>
        </div>
    </div>
    <div id="responseLoading"><img width="75" height="75" src="<?php echo $this->getSkinUrl('images/detailedreview/ajax-loader.gif'); ?>" alt="<?php echo $this->__('Please, wait...') ?>"/></div>
</div>
<div id="imageLoading" style="display: none"><img width="50" height="50" src="<?php echo $this->getSkinUrl('images/detailedreview/ajax-loader.gif'); ?>" alt="<?php echo $this->__('Please, wait...') ?>"/></div>
<!-- the block does not blink when loading need this script -->
<script type="text/javascript">
    document.getElementById('feedback').style.display = 'none';
</script>
