<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
	$_images = $this->getCategoryGalleryImages($_product);
?>
<div class="product-color">
	<?php if(count($_images)):?>
    <div class="product-color-title">
        <h4><?php echo $this->__('Color:') ?></h4>
    </div>
	<?php endif; ?>
	
    <?php foreach($_images as $_image){?>
        <a class="product-swatch-color" onclick="return false;" rel="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(315); ?>" href="#">
            <img src="<?php echo '/media/swatchIcons/30'.$_image['swatchimage']?>" alt="<?php echo $_image['swatchimage_label']?>" />
            <input type="hidden" value="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(700); ?>">
        </a>
<?php } ?>

</div>
<div class="color-title"></div>
<script type="text/javascript">
    jQuery('.product-swatch-color').click(function() {
        jQuery('.product-swatch-color img').removeClass('selected');
        jQuery(this).find("img").addClass('selected');
        jQuery('.product-img-box .main-product-image').find("img").attr('src',jQuery(this).attr('rel'));
        jQuery('#magic-zoom-trigger').attr('href',jQuery(this).find('input').attr('value'));
        jQuery('.zoom-button').find('#image-zoom-src').attr('value',jQuery(this).find('input').attr('value'));
        initMagicZoom();
        return false;
    });
    var def_img = '';
    jQuery('.product-swatch-color').mouseenter(function() {
        def_img = jQuery('.product-img-box .main-product-image').find("img").attr('src');
        jQuery('.product-img-box .main-product-image').find("img").attr('src',jQuery(this).attr('rel'));
        jQuery(this).parent('.product-color').next().html(jQuery(this).find('img').attr('alt'));
    }).mouseleave(function() {
        jQuery(this).parent('.product-color').next().html('');
        if(!jQuery(this).find("img").hasClass('selected'))
            jQuery('.product-img-box .main-product-image').find("img").attr('src',def_img);
    });
    jQuery(document).ready(function() {

    });
</script>
<style type="text/css">
    .product-swatch-color img.selected {
        border: 2px #FF0000 solid;
    }
</style>