<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
    $_images = $this->getCategoryGalleryImages($_product);
?>


<?php if($_images){
    foreach($_images as $_image){?>
    <img
        src="<?php echo '/media/swatchIcons/20'.$_image['swatchimage']?>"
        alt="<?php echo $_image['swatchimage_label']?>"
        title="<?php echo $_image['label']?>"
        rel="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile())->resize(207); ?>"
        width="20" height="20" class="category-product-swatch"
        />
    <?php
        //print_r($_image->toArray());
    }
}
?>