<script>

/*
 * This script is useless without the base borderpay checkout page extension!
 * If you see a variable used here that isn't defined anywhere check there
 * [template dir, probably in base/default]/borderpay/checkout/onepage/extension.phtml
 */

function validate() {
    isValid = true;
    if (!checkout.validator.validate()) {
        isValid = false;
    }
    
    for (i in checkout.sectionsToValidate) {
        if (typeof checkout.sectionsToValidate[i] === 'function') {
            continue;
        }
        if (!checkout.sectionsToValidate[i].validate()) {
            isValid = false;
        }
    }
    FireCheckout.Messenger.clear('checkout-review-submit');
    $$('#checkout-review-submit .checkout-agreements input[type="checkbox"]').each(function(el) {
        if (!el.checked) {
            FireCheckout.Messenger.add(checkout.acceptAgreementText, 'agreements-wrapper', 'error');
            isValid = false;
            return isValid;
        }
    }.bind(checkout));

    if (!isValid) {
        // scroll to error
        var validationMessages = $$('.validation-advice, .messages').findAll(function(el) {
            return false
        });
        if (!validationMessages.length) {
            return false;
        }

        var viewportSize = document.viewport.getDimensions();
        var hiddenMessages = [];
        var needToScroll = true;

        validationMessages.each(function(el) {
            var offset = el.viewportOffset();
            if (offset.top < 0
                || offset.top > viewportSize.height
                || offset.left < 0
                || offset.left > viewportSize.width) {

                hiddenMessages.push(el);
            } else {
                needToScroll = false;
            }
        });

        if (needToScroll) {
            Effect.ScrollTo(validationMessages[0], {
                duration: 1,
                offset: -20
            });
        }
        return isValid;
    } else {
        return true;
    }
}

jQuery(document).ready(function($) {
    $orderButton = $('button[title="Place Order"]');
    
    // Reroute the submit order button to use our own handler when BorderPay is selected
    $form.find('input[name="payment[method]"]').live('change', function(e) {
        if ($form.find('input[name="payment[method]"]:checked').val() == 'borderpay') {
            $orderButton.unbind('click');
            $orderButton.attr('onclick', null);
            $orderButton.click(firecheckoutDispatch);
        } else {
            $orderButton.unbind('click');
            $orderButton.attr('onclick', 'checkout.save()');
        }
    });
    $form.find('input[name="payment[method]"]').trigger('change');
    
    function firecheckoutDispatch() {
        checkout.setLoadWaiting(true);
        if (! validate()) {
            return;
        }
        $('#fingerprint').val($('#ioBlackBox').val());
        var formData = $form.serialize();
        $.ajax({
            type: 'POST',
            url: '<?php echo Mage::getUrl("checkout/onepage/saveAdditionalData"); ?>',
            dataType: 'json',
            data: formData,
            success: function(){
                var paymentService = $('#borderpay_service').val();
                if ( ! paymentService) {
                    checkout.setLoadWaiting(false);
                    return;
                } else {
                    saveOther();
                }
            },
            error: function(){ alert('Internal error.'); }
        });
    }
    
})
</script>