<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <mageworkshophq@gmail.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */

/** @var MageWorkshop_DetailedReview_Block_Rating_Entity_Detailed $this */
$currentUrl = preg_replace('/\?.*/', '', $this->helper('core/url')->getCurrentUrl());
$helperDetailedreview = $this->helper('detailedreview');
$isCustomerLogged = $this->helper('customer')->isLoggedIn();
$isGuestAllowToWrite = $this->helper('review')->getIsGuestAllowToWrite();
$arrayQtyMarks = $this->getQtyMarks();
$sum = $this->getCountReviewsWithRating();
$ratingsEnabled = Mage::helper('detailedreview')->checkEnabledRatings();
$showRating = Mage::helper('detailedreview')->checkFieldAvailable('review_graph', 'info');
$isShowFilters = Mage::getStoreConfig('detailedreview/show_review_info_settings/allow_result_filters');
?>
<div class="review-top" <?php if (!$isShowFilters) : ?> style="border-bottom: 1px solid #CCCCCC;" <?php endif; ?>>
    <div class="review-average-info">
        <?php
            $summary = $this->getSummary();
            if ($summary && $ratingsEnabled):
        ?>
            <div class="average-rating">
                <div class="average-caption"><span class="average-rating-text"><?php echo $this->__('Average Rating:') ?></span></div>
                <div class="rating-stars-views" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo ceil($summary) ?>%;">
                            <meta itemprop="worstRating" content="1"/>
                            <meta itemprop="ratingValue" content="<?php echo ceil($summary) ?>" />
                            <meta itemprop="bestRating" content="100" />
                        </div>
                    </div>
                    <div class="average-based-on">
                        <?php
                        if ($sum == 1) {
                            echo $this->__(' %s review', $sum);
                        } else {
                            echo $this->__(' %s reviews', $sum);
                        }
                        echo '<meta itemprop="reviewCount" content="' . $sum . '"/>';
                        ?>
                    </div>
                </div>
            </div>
        <?php endif; ?>
        <div class="button-write-review">
            <?php if ( !$helperDetailedreview->isUserAbleToWriteReview() ): ?>
                <span class="error"><?php echo $this->__('You are not Allowed to Write a Review.'); ?></span>
            <?php else: ?>
                <?php $redirectUrl = $currentUrl  . $helperDetailedreview->getCurrentUrlWithNewParam('show_popup','1'); ?>
                <input type="hidden" value="<?php echo $this->escapeHtml($redirectUrl); ?>" />
                <input type="hidden" value="<?php echo $this->helper('core/url')->getEncodedUrl($redirectUrl);?>" />
                <input class="review-dialog" type='button' value="<?php echo $this->__('Write A Review') ?>" />
            <?php endif; ?>
        </div>
    </div>
    <div class="ratings-and-size">
        <?php if ($showRating && $summary && $ratingsEnabled): ?>
            <div class="review-right">
                <div class="separate-rating">
                    <?php for ($key=0;$key<5;$key++){ ?>
                        <div class="mark-rating">
                            <div class="rating-box">
                                <div class="rating"><span><?php echo (5-$key); ?><?php echo $this->__(' star'); ?></span></div>
                            </div>
                            <div class="scroll-box">
                                <div class="scroll-rating" style="width:<?php echo ( isset($arrayQtyMarks[5-$key]) && $sum != 0 ) ? ceil(100*$arrayQtyMarks[5-$key]/$sum) : 0 ?>%;"></div>
                            </div>
                            <div class="rating-percent">
                                <span><?php echo ( isset ($arrayQtyMarks[5-$key]) && $sum != 0 ) ? $arrayQtyMarks[5-$key] : '0'; ?></span>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="clearboth"></div>
                </div>
            </div>
        <?php endif; ?>
        <?php if ( $helperDetailedreview->checkFieldAvailable('sizing', 'form') && $sizing = $this->getAverageSizing()):?>
            <div class="average-sizing-box">
                <div class="average-caption"><span><?php echo $this->__('Size') ?></span></div>
                <?php $reviewSizing = Mage::getSingleton('detailedreview/review_sizing'); ?>
                <div class="sizing-bar average">
                    <div style="width:<?php echo $reviewSizing->getOptionWidth($sizing) ?>%;"></div>
                    <p class="sizing-pointer" style="margin-left: <?php echo($reviewSizing->getOptionWidth($sizing) . '%'); ?>"></p>
                    <p class="sizing-label" style="margin-left: <?php echo($reviewSizing->getOptionWidth($sizing) . '%'); ?>;right: <?php echo $reviewSizing->getIndent($sizing); ?>">
                          <?php echo $reviewSizing->getOptionValue($sizing); ?>
                    </p>
                </div>
            </div>
        <?php endif;?>
    </div>
    <?php if ($isShowFilters) : ?>
        <div class="review-left">
            <div class="filters">
                <h4><?php echo $this->__('Result filter:') ?></h4>
                <ul class="review-date-filters" id="dateFilter" onchange="setLocation(this.value)">
                    <li class="top-dropdown"><a href="javascript:void(0)" rel="nofollow" class="dateFilter"><span class="top-title"><?php echo $this->__('All Reviews')?></span></a></li>
                    <?php foreach ($this->getAvailableDateRanges() as $k => $v): ?>
                        <?php $sumByRange = $this->getQtyByRange($k); ?>
                        <?php if(($k == 1) && (!Mage::getSingleton( 'customer/session' )->isLoggedIn())) continue; ?>
                        <li <?php if ($helperDetailedreview->isInGetParams('st', $k)):?> class="active"<?php endif; ?>>
                            <a data-type="range-filter" data-value="<?php echo $k; ?>" href="#" rel="nofollow">
                                <span class="range-filter-title"><?php echo $v .'<span class="range-filter-value"> (' . $sumByRange . ')</span>';?></span>
                            </a>
                        </li>
                    <?php endforeach;?>
                </ul>
            </div>
            <div class="form-filters-wrapper">
                <ul class="attr-rating">
                    <?php $reviewFilter = 1; ?>
                    <?php foreach ( $this->getAvailableFilterAttributes() as $k => $v ):?>
<!--                        --><?php //if ($helperDetailedreview->checkAvailableFilter($k)):?>
                            <li>
                                <input id="reviewfilter-<?php echo $reviewFilter ?>" type="checkbox" data-type="review-filter" data-filter="<?php echo $k; ?>" <?php if ($helperDetailedreview->isInGetParams($k,'true')):?>checked="checked"<?php endif;?> value="<?php echo $k; ?>"/>
                                <span></span>
                                <label for="reviewfilter-<?php echo $reviewFilter ?>"><?php echo $this->__($v);?></label>
                            </li>
<!--                        --><?php //endif; ?>
                        <?php $reviewFilter++; ?>
                    <?php endforeach;?>
                </ul>
                <form method="get" action="<?php echo htmlspecialchars( $this->helper('core/url')->getCurrentUrl() ); ?>" id="review_search_mini_form" data-type="search">
                    <div class="form-search">
                        <input type="hidden" value="1" name="feedback"/>
                        <?php if ($request = $this->getRequest()) : ?>
                            <?php foreach ($request->getParams()  as $key => $value): ?>
                                <?php if ($key == 'feedback' || $key == 'keywords') continue; ?>
                                <?php if (is_array($value)) $value = serialize($value); ?>
                                <input type="hidden" value="<?php echo $this->escapeHtml($value) ?>" name="<?php echo $this->escapeHtml($key) ?>"/>
                            <?php endforeach; ?>
                        <?php endif; ?>
                        <?php $keywords = isset($request) ? $request->getParam('keywords') : ''; ?>
                        <input type="text" class="input-text ac-off" value="<?php echo $this->escapeHtml($keywords) ?>" name="keywords" placeholder="<?php echo $this->__('search in reviews') ?>" id="review-search"/>
                        <button type="submit" class="search-review-button"><span><span><?php echo $this->__('Go') ?></span></span></button>
                        <script type="text/javascript">
                            //<![CDATA[
                            //                         var searchReviewForm = new Varien.searchForm('review_search_mini_form', 'review-search', 'Search in reviews');
                            document.observe("dom:loaded", function() {
                                'use strict';
                                (function($){
                                    $('.ac-off').placeholder();
                                    $(".ac-off").attr("autocomplete", "off");
                                })(DRjQuery)
                            });
                            //                        $$(".ac-off").each(function(el){el.autocomplete = 'off';})
                            //]]>
                        </script>
                    </div>
                </form>
            </div>
            <div class="review-sorts">
                <?php /* <span>Showing <?php echo $sum;?> of <?php echo $tempSum;?> reviews <a href="<?php echo $currentUrl?>?feedback=1#feedback" >Clear Filters</a></span> */ ?>
                <?php $selectedOrder = $this->getCurrentSorting();
                $availableSorts = $this->getAvailableSorts($ratingsEnabled); ?>
                <ul class="select-review-sorts" onchange="setLocation(this.value)">
                    <li class="top-dropdown-sorts"><a href="javascript:void(0)" rel="nofollow" class="sortsLink"><span class="top-title"><?php echo $this->__('Date - Newest First')?></span></a></li>
                    <?php foreach ($availableSorts as $sort => $label): ?>
                        <li style="width:<?php echo 100/count($availableSorts)?>%;" <?php if ($selectedOrder == $sort): ?> class="selected"<?php endif; ?> data-type="sort" data-sort="<?php echo $sort; ?>"><?php echo $this->__($label) ?></li>
                    <?php endforeach;?>
                </ul>
            </div>
        </div>
    <?php endif; ?>
</div>
<div id="star-five"></div>
