<?php $_shipment=$this->getShipment() ?>
<?php $_order=$this->getOrder() ?>
<?php if ($_shipment && $_order && $_shipment->getAllTracks()): ?>
<table cellspacing="0" cellpadding="0" border="0" width="650" style="border:1px solid #EAEAEA;">
    <thead>
        <tr>
            <th align="left" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Shipped By') ?></th>
            <th align="center" bgcolor="#EAEAEA" style="font-size:13px; padding:3px 9px"><?php echo $this->__('Tracking Number') ?></th>
        </tr>
    </thead>
    <tbody>
    <?php $i=0; foreach ($_shipment->getAllTracks() as $_item): $i++ ?>
        <tr <?php echo $i%2?'bgcolor="#F6F6F6"':'' ?>>
            <?php if ($_order->getShippingCarrier()->getCarrierCode() == 'bordership'): ?>
                <?php if ($_item->getCarrierCode() == 'bordership'): ?>
                    <td align="left" valign="top" style="padding:3px 9px"><?php echo $_item->getTitle() ?></td>
                    <td align="center" valign="top" style="padding:3px 9px">
                        <a href="http://track.borderjump.com/?track_id=<?php echo $_item->getNumber() ?>"><?php echo $_item->getNumber() ?></a>
                    </td>
                <?php endif; ?>
            <?php else: ?>
                <td align="left" valign="top" style="padding:3px 9px"><?php echo $_item->getTitle() ?></td>
                <td align="center" valign="top" style="padding:3px 9px"><?php echo $_item->getNumber() ?></td>
            <?php endif; ?>
        </tr>
    <?php endforeach ?>
    </tbody>
</table>
<?php endif; ?>
