<div id="ascommercebug_lookup_container">
	<p>Enter a URI (<span class="classname">catalog/product</span>) or a class name 
	(<span class="classname">Mage_Catalog_Model_Product</span>).</p>
	<p>Using URI context
	<select id="ascommercebug_select_context">
		<option value="all">All</option>
		<option value="model">Model</option>
		<option value="block">Block</option>								
		<option value="helper">Helper</option>				
	</select>, 
	<input type="text" id="ascommercebug_text_lookup_uri"/>  <button id="ascommercebug_but_lookup" class="fg-button ui-state-default ui-corner-all">Resolves To</button></p>
	<div id="ascommercebug_lookup_results">
	</div>
</div>