<div id="ascommercebug_controllers_results">
	<table id="ascommercebug_controllers_results_table" class="tablesorter">
		<thead>
			<tr>
				<th>
					Label
				</th>
				<th>
					Value
				</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>
					Controller Class Name
				</td>
				<td>
					<span id="ascommercebug_controllers_classname" class="classname"></span> 
					<br />
					<span id="ascommercebug_controllers_filename" class="pathinfo"></span> 
				</td>
			</tr>
			<tr>
				<td>
					Full Action Name
				</td>
				<td>
					<span id="ascommercebug_controllers_full_actionname"></span>
				</td>
			</tr>
			<tr>
				<td>
					Module Name
				</td>
				<td>
					<span id="ascommercebug_controllers_modulename"></span>
				</td>
			</tr>
			<tr>
				<td>
					Controller Name
				</td>
				<td>
					<span id="ascommercebug_controllers_controllername"></span>
				</td>
			</tr>
			<tr>
				<td>
					Action Name
				</td>
				<td>
					<span id="ascommercebug_controllers_actionname"></span>
				</td>
			</tr>
			<tr>
				<td>
					Path Info
				</td>
				<td>
					<span id="ascommercebug_controllers_pathinfo"></span>
				</td>
			</tr>
		</tbody>
	</table>
</div>
