<?php
/**
 * @category    design
 * @package     borderpay
 */
?>
<?php $_code=$this->getMethodCode() ?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <input type="hidden" name="payment[transaction_type]" id="transaction_type"></input>
        <div class="input-box">
<label for="<?php echo $_code ?>_service" class="required"><em>*</em>
            <select id="<?php echo $_code ?>_service" name="payment[service]" title="<?php echo $this->__('Payment Service') ?>" class="required-entry">
                <option value=""><?php echo $this->__('-- Select Payment Type --') ?></option>
            <?php $response = $this->getPaymentMethods(); ?>
            <?php if ($response): ?>
                <?php foreach ($response as $k => $service): ?>
                    <option value="<?php echo $service; ?>"><?php echo $k; ?></option>
                <?php endforeach; ?>
            <?php endif; ?>
            </select>
        </div>
    </li>
    <li id="third-party-message">
        <input id="ACSUrl" type="hidden" name="ACSUrl"/>
        <input id="MD" type="hidden" name="MD"/>
        <input id="PaReq" type="hidden" name="PaReq"/>
        <input id="TermUrl" type="hidden" name="TermUrl"/>
        <input id="fingerprint" type="hidden" name="fingerprint"/>
        <p id="borderpay-external" style="display:none;">You will be taken to an external page to complete your payment.</p>
    </li>
    <li>
        <ul id="payment_cc_form" style="display:none;">
            <li>
                <?php Mage::getSingleton('core/session', array('name' => 'frontend')); ?>
                <?php $billing = Mage::getSingleton('checkout/session')->getQuote()->getBillingAddress(); ?>
                <label for="<?php echo $_code ?>_cc_name" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_name" name="payment[cc_name]" title="<?php echo $this->__('Name on Card') ?>" class="input-text" value="<?php echo $billing->getName(); ?>" />
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_type" class="required"><em>*</em><?php echo $this->__('Credit Card Type') ?></label>
                <div class="input-box">
                    <select id="<?php echo $_code ?>_cc_type" name="payment[cc_type]" class="required-entry validate-cc-type-select">
                        <option value=""><?php echo $this->__('--Please Select--')?></option>
                    <?php $_ccType = $this->getInfoData('cc_type') ?>
                    <?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
                        <option value="<?php echo $_typeCode ?>"<?php if($_typeCode==$_ccType): ?> selected="selected"<?php endif ?>><?php echo $_typeName ?></option>
                    <?php endforeach ?>
                    </select>
                </div>
            </li>
            <li>
                <label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
                <div class="input-box">
                    <input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text validate-cc-number validate-cc-type" value="" />
                </div>
            </li>
            <li id="<?php echo $_code ?>_cc_type_exp_div">
                <label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <select id="<?php echo $_code ?>_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp required-entry">
                        <?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
                        <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                    <div class="v-fix">
                        <?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
                        <select id="<?php echo $_code ?>_expiration_yr" name="payment[cc_exp_year]" class="year required-entry">
                        <?php foreach ($this->getCcYears() as $k=>$v): ?>
                            <option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                        <?php endforeach ?>
                        </select>
                    </div>
                </div>
            </li>
            <?php echo $this->getChildHtml() ?>
            <?php if($this->hasVerification()): ?>
            <li id="<?php echo $_code ?>_cc_type_cvv_div">
                <label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
                <div class="input-box">
                    <div class="v-fix">
                        <input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv required-entry validate-cc-cvn" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" />
                    </div>
                    <a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
                </div>
            </li>
            <?php endif; ?>

            <?php if ($this->hasSsCardType()): ?>
            <li id="<?php echo $_code ?>_cc_type_ss_div">
                <ul class="inner-form">
                    <li class="form-alt"><label for="<?php echo $_code ?>_cc_issue" class="required"><em>*</em><?php echo $this->__('Switch/Solo/Maestro Only') ?></label></li>
                    <li>
                        <label for="<?php echo $_code ?>_cc_issue"><?php echo $this->__('Issue Number') ?>:</label>
                        <span class="input-box">
                            <input type="text" title="<?php echo $this->__('Issue Number') ?>" class="input-text validate-cc-ukss cvv" id="<?php echo $_code ?>_cc_issue" name="payment[cc_ss_issue]" value="" />
                        </span>
                    </li>
                    <li>
                        <label for="<?php echo $_code ?>_start_month"><?php echo $this->__('Start Date') ?>:</label>
                        <div class="input-box">
                            <div class="v-fix">
                                <select id="<?php echo $_code ?>_start_month" name="payment[cc_ss_start_month]" class="validate-cc-ukss month">
                                    <?php foreach ($this->getCcMonths() as $k=>$v): ?>
                                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_month')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                            <div class="v-fix">
                                <select id="<?php echo $_code ?>_start_year" name="payment[cc_ss_start_year]" class="validate-cc-ukss year">
                                    <?php foreach ($this->getSsStartYears() as $k=>$v): ?>
                                        <option value="<?php echo $k?$k:'' ?>"<?php if($k==$this->getInfoData('cc_ss_start_year')): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
                                    <?php endforeach ?>
                                </select>
                            </div>
                        </div>
                    </li>
                    <li class="adv-container">&nbsp;</li>
                </ul>
                <script type="text/javascript">
                    //<![CDATA[
                    var SSChecked<?php echo $_code ?> = function() {
                        var elm = $('<?php echo $_code ?>_cc_type');
                        if (['SS','SM','SO'].indexOf(elm.value) != -1) {
                            $('<?php echo $_code ?>_cc_type_ss_div').show();
                        } else {
                            $('<?php echo $_code ?>_cc_type_ss_div').hide();
                        }
                    };
                    
                    Event.observe($('<?php echo $_code ?>_cc_type'), 'change', SSChecked<?php echo $_code ?>);
                    SSChecked<?php echo $_code ?>();
                    //]]>
                </script>
            </li>
            <?php endif; ?>
        </ul>
    </li>
</ul>
<script>
jQuery(document).ready(function($){

    // Check for the BorderPay service change and update the form
    var paypalDirect =  '2';
    var safetypay =     '5';
    var planetPayment = '6';
    
    var $ccFormElements = $('ul#payment_cc_form').html();
    $('#borderpay_service').live('change', function(e){
        $payment_form = $('ul#payment_cc_form');
        
        var service = $(this).val();
        if (service == planetPayment) {
            $('p#borderpay-external').hide();
            $payment_form.html($ccFormElements);
            $('input, select', $payment_form).attr('disabled', false);
            $payment_form.show();
            $('input#transaction_type').val('CC');
        } else if (service == paypalDirect) {
            $('p#borderpay-external').show();
            $payment_form.hide();
            $payment_form.empty();
            $('input#transaction_type').val('PP');
        } else if (service == safetypay) {
            $('p#borderpay-external').show();
            $payment_form.hide();
            $payment_form.empty();
            $('input#transaction_type').val('SP');
        } else {
            $('p#borderpay-external').hide();
            $payment_form.hide();
            $payment_form.empty();
            $('input#transaction_type').val('');
        }
    });
});
</script>