<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
?>
<?php if($crumbs && is_array($crumbs)): ?>
<div class="breadcrumbs" xmlns:v="http://rdf.data-vocabulary.org/#">
    <ul>
        <?php foreach($crumbs as $_crumbName=>$_crumbInfo): ?>
            <li class="<?php echo $_crumbName ?>">
            <span typeof="v:Breadcrumb">
				<?php if($_crumbInfo['link']): ?>
					<a href="<?php echo $_crumbInfo['link'] ?>" title="<?php echo $this->htmlEscape($_crumbInfo['title']) ?>" rel="v:url" property="v:title"><?php echo $this->htmlEscape($_crumbInfo['label']) ?></a>
				<?php elseif($_crumbInfo['last']): ?>
					<strong><?php echo $this->htmlEscape($_crumbInfo['label']) ?></strong>
				<?php else: ?>
					<?php echo $this->htmlEscape($_crumbInfo['label']) ?>
				<?php endif; ?>
				<?php if(!$_crumbInfo['last']): ?>
					&nbsp; &raquo;
				<?php endif; ?>
			</span>
            </li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>