<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2013 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
$_snippets = $this->getProductSnippets();
?>
<?php if($this->getSnippetsEnabled() && $_snippets): ?>	
	<!--BEGIN: Rich Snippets-->
	<?php if($this->getMarkup() == 'hidden'): ?>
		<div itemscope itemtype="http://schema.org/Product">
			<meta itemprop="name" content="<?php echo $this->escapeHtml($_snippets->getName()); ?>" />
			<?php if($this->getSnippetsDescription()): ?>
				<meta itemprop="description" content="<?php echo $this->escapeHtml($this->getDescription()); ?>" />	
			<?php endif; ?>
			<?php if($this->getSnippetsUniqueIdEnabled() && $this->getProductUniqueId()): ?>	
				<?php echo $this->getProductUniqueId(); ?>
			<?php endif; ?>
			<?php if($this->getSnippetsBrand() && $this->getProductBrand()): ?>
				<div itemprop="manufacturer" itemscope itemtype="http://schema.org/Organization">
					<meta itemprop="name" content="<?php echo $this->escapeHtml($this->getProductBrand()); ?>" />
				</div>
			<?php endif; ?>
			<div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
				<meta itemprop="itemCondition" href="http://schema.org/NewCondition" content="New" />
				<meta itemprop="seller" content="<?php echo $this->escapeHtml($this->getSnippetsSeller()); ?>" />
				<meta itemprop="priceCurrency" content="<?php echo Mage::app()->getStore()->getBaseCurrencyCode(); ?>" />
				<meta itemprop="price" content="<?php echo $this->helper('core')->currency(Mage::helper('tax')->getPrice($_snippets, $_snippets->getFinalPrice()), true, false); ?>" />
				<?php if($this->getSnippetsStock()): ?>
					<link itemprop="availability" href="<?php echo $this->getProductAvailability(); ?>">
				<?php endif; ?>
			</div>
			<?php if($this->getReviewSnippets() && $this->getSnippetsReviewEnabled()) : ?>
				<?php echo $this->getReviewSnippets(); ?>
			<?php endif; ?>	  
		</div>
	<?php else: ?>
		<div class="std">
			<div class="snippets">
				<div itemscope itemtype="http://schema.org/Product">
				  <div class="prod-thumb">
					<img itemprop="image" src="<?php echo Mage::helper('catalog/image')->init($_snippets, 'image')->resize(75); ?>">
				  </div>	
				  <div class="content">
					  <p><span itemprop="name" class="product-name"><?php echo $this->escapeHtml($_snippets->getName()); ?></span>  
					  <?php if($this->getSnippetsUniqueIdEnabled() && $this->getProductUniqueId()): ?>	
						 <?php echo Mage::helper('snippets')->__('Product') ?>: <?php echo $this->getProductUniqueId(); ?>
					  <?php endif; ?>
					  <?php if($this->getSnippetsBrand() && $this->getProductBrand()): ?>
						<?php echo Mage::helper('snippets')->__('Brand') ?>: <span itemprop="brand"><?php echo $this->escapeHtml($this->getProductBrand()); ?></span> 
					  <?php endif; ?>		  
					  </p>
					  <?php if($this->getReviewSnippets() && $this->getSnippetsReviewEnabled()) : ?>
						<?php echo $this->getReviewSnippets(); ?>
					  <?php endif; ?>	  
					  <?php if($this->getSnippetsDescription()): ?>
						  <span itemprop="description"><?php echo $this->escapeHtml($this->getDescription()); ?></span>
					  <?php endif; ?>
					  <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">
						<?php if($_snippets->getTypeId() == 'grouped'): ?>
							<?php echo Mage::helper('snippets')->__('Starting at:') ?> <span itemprop="price"><?php echo $this->helper('core')->currency($this->getProductPrice(), true, false); ?></span>
						<?php else: ?>
							<?php echo Mage::helper('snippets')->__('Price:') ?> <span itemprop="price"><?php echo $this->helper('core')->currency($this->getProductPrice(), true, false); ?></span>						
						<?php endif; ?>
						<meta itemprop="priceCurrency" content="<?php echo Mage::app()->getStore()->getBaseCurrencyCode(); ?>" />
						<?php if($this->getSnippetsStock()): ?>
							<?php echo $this->getProductAvailability(); ?>
						<?php endif; ?>		  
					</div>
				  </div>			
				</div>
			</div>
		</div>
	<?php endif; ?>
	<!--END: Rich Snippets-->
<?php endif; ?>