<div class="clickdesk-widget">

    <!-- ClickDesk Live Chat Service for websites -->
    <!--script type='text/javascript'>
        var _glc = _glc || [];
        jQuery(function () {
            _glc.push('<?php echo $this->getWidgetId(); ?>');
            var glcpath = (('https:' == document.location.protocol) ? 'https://my.clickdesk.com/clickdesk-ui/browser/' :
                'http://my.clickdesk.com/clickdesk-ui/browser/');
            var glcp = (('https:' == document.location.protocol) ? 'https://' : 'http://');
            var glcspt = document.createElement('script');
            glcspt.type = 'text/javascript';
            glcspt.async = true;
            glcspt.defer = true;
            glcspt.src = glcpath + 'livechat-new.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(glcspt, s);
        });
    </script-->
    <!-- End of ClickDesk -->

</div>
