<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
?>
<?php if($this->getTwitterEnabled() && $this->getTwitterUser()): ?>	
<meta name="twitter:card" content="product" />
<meta name="twitter:url" content="<?php echo $this->getTwitterUrl(); ?>" />
<meta name="twitter:title" content="<?php echo $this->getTwitterTitle(); ?>"/>
<?php if($description = $this->getTwitterDescription()): ?>
<meta name="twitter:description" content="<?php echo $description; ?>" />
<?php endif; ?>
<?php if($image = $this->getTwitterImageUrl()): ?>
<meta name="twitter:image" content="<?php echo $image; ?>" />
<?php endif; ?>
<meta name="twitter:site" content="<?php echo $this->getTwitterUser(); ?>" />
<meta name="twitter:creator" content="<?php echo $this->getTwitterUser(); ?>" />
<meta name="twitter:data1" content="<?php echo $this->getTwitterPrice(); ?>" />
<meta name="twitter:label1" content="PRICE" />
<meta name="twitter:data2" content="<?php echo $this->getTwitterAvailability(); ?>" />
<meta name="twitter:label2" content="AVAILABILITY" />
<?php endif; ?>