<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
?>
<?php if($this->getSnippetsEnabled() && ($_snippets = $this->getSnippets())): ?>	
<address class="copyright">

		<div itemscope itemtype="http://schema.org/Product">	
			<ul class="snippets-fields">
				<?php if($reviews = $this->getReviews()): ?>
					<li><?php echo $reviews; ?></li>
				<?php else: ?>
					<li><?php echo '<span itemprop="name">' . $this->escapeHtml($_snippets->getName()) . '</span>'; ?></li>
				<?php endif; ?>
				<li><?php echo $this->getOffers(); ?></li>
				<?php if($extafields = $this->getExtraFields()): ?>
					<?php foreach($this->getExtraFields() as $field): ?>
						<li><?php echo Mage::helper('snippets')->__($field['label']) . ': ' . $field['value']; ?></li>
					<?php endforeach; ?>
				<?php endif; ?>	
			</ul>			
		</div>
	
</address>	
<?php endif; ?>