<?php
/**
 * Magmodules.eu - http://www.magmodules.eu - info@magmodules.eu
 * =============================================================
 * NOTICE OF LICENSE [Single domain license]
 * This source file is subject to the EULA that is
 * available through the world-wide-web at:
 * http://www.magmodules.eu/license-agreement/
 * =============================================================
 * @category    Magmodules
 * @package     Magmodules_Snippets
 * @author      Magmodules <info@magmodules.eu>
 * @copyright   Copyright (c) 2014 (http://www.magmodules.eu)
 * @license     http://www.magmodules.eu/license-agreement/  
 * =============================================================
 */
?>
<?php if($this->getSnippetsEnabled() && ($_snippets = $this->getSnippets())): ?>	
	<!--BEGIN: Rich Snippets-->
		<div class="std">
			<div class="snippets">
				<div itemscope itemtype="http://schema.org/Product">
					<?php if($thumb = $this->getThumbnail()): ?>
						<div class="prod-thumb">
							<img itemprop="image" src="<?php echo $thumb; ?>">
						</div>		
					<?php endif; ?>
					<div class="content">
					  	<p>
					  		<span itemprop="name" class="product-name"><?php echo $this->escapeHtml($_snippets->getName()); ?></span>.					  		
							<?php if($description = $this->getDescription()): ?>
								<span itemprop="description"><?php echo $this->escapeHtml($description); ?></span>
							<?php endif; ?>
					  	</p>
						<?php if($reviews = $this->getReviewSnippets()): ?>
							<?php echo $reviews; ?>
						<?php endif; ?>	  					
						<ul class="snippets-fields">
							<li><?php echo $this->getOffers(); ?></li>
							<?php if($extafields = $this->getExtraFields()): ?>
								<?php foreach($this->getExtraFields() as $field): ?>
									<li><?php echo Mage::helper('snippets')->__($field['label']) . ': ' . $field['value']; ?></li>
								<?php endforeach; ?>
							<?php endif; ?>	
						</ul>			
					</div>			
				</div>
			</div>
		</div>
	<!--END: Rich Snippets-->
<?php endif; ?>