<?php
/**
 * MageWorkshop
 * Copyright (C) 2016 MageWorkshop <mageworkshophq@gmail.com>
 *
 * @category   MageWorkshop
 * @package    MageWorkshop_DetailedReview
 * @copyright  Copyright (c) 2016 MageWorkshop Co. (http://mage-workshop.com)
 * @license    http://opensource.org/licenses/gpl-3.0.html GNU General Public License, version 3 (GPL-3.0)
 * @author     MageWorkshop <mageworkshophq@gmail.com>
 */
?>
<?php if($this->getCollection()->getSize()): ?>

    <?php $currentProduct = Mage::registry('current_product'); ?>
    <?php $currentProductUrl = $currentProduct->getProductUrl(); ?>

    <?php if($this->getUseContainer()): ?>
        <div class="pager pager-no-toolbar">
    <?php endif ?>

    <?php if($this->getShowAmounts() || $this->getShowPerPage()): ?>
        <div class="count-container">
            <?php if($this->getShowAmounts()): ?>
                <?php if($this->getLastPageNum()>1): ?>
                    <p class="amount amount--has-pages">
                        <?php echo $this->__('%s-%s of %s', $this->getFirstNum(), $this->getLastNum(), $this->getTotalNum()) ?>
                    </p>
                <?php else: ?>
                    <p class="amount amount--no-pages">
                        <strong><?php echo $this->__('%s Item(s)', $this->getTotalNum()) ?></strong>
                    </p>
                <?php endif; ?>
            <?php endif ?>

            <?php if($this->getShowPerPage()): ?>
                <div class="limiter">
                    <label><?php echo $this->__('Show') ?></label>
                    <select title="<?php echo $this->__('Results per page'); ?>" data-type="limiter">
                    <?php foreach ($this->getAvailableLimit() as  $_key=>$_limit): ?>
                        <option value="<?php echo $_key; ?>" <?php if($this->isLimitCurrent($_key)): ?> selected="selected"<?php endif ?>>
                            <?php echo $_limit ?>
                        </option>
                    <?php endforeach; ?>
                    </select>
                </div>
            <?php endif ?>
        </div>
    <?php endif; ?>

    <?php if($this->getLastPageNum()>1): ?>
        <div class="pages">
            <strong><?php echo $this->__('Page:') ?></strong>
            <ol>
                <?php if (!$this->isFirstPage()): ?>
                    <li>
                        <a class="previous<?php if(!$this->getAnchorTextForPrevious()): ?> i-previous<?php endif;?>" href="<?php echo($currentProductUrl . '?r_p=' . $this->getPreviousPageNumber()); ?>" data-type="r-page" data-number="<?php echo $this->getPreviousPageNumber(); ?>" title="<?php echo $this->__('Previous') ?>">
                            <?php if(!$this->getAnchorTextForPrevious()): ?>
                                <?php echo $this->__('Previous') ?>
                            <?php else: ?>
                                <?php echo $this->getAnchorTextForPrevious() ?>
                            <?php endif;?>
                        </a>
                    </li>
                <?php endif;?>

                <?php if ($this->canShowFirst()): ?>
                    <li><a class="first" href="<?php echo($currentProductUrl . '?r_p=' . $this->getFirstPageNumber()); ?>" data-type="r-page" data-number="<?php echo $this->getFirstPageNumber(); ?>">1</a></li>
                <?php endif;?>

                <?php if ($this->canShowPreviousJump()): ?>
                    <li><a class="previous_jump" title="" href="<?php echo($currentProductUrl . '?r_p=' . $this->getPreviousJumpNumber()); ?>" data-type="r-page" data-number="<?php echo $this->getPreviousJumpNumber(); ?>">...</a></li>
                <?php endif;?>

                <?php foreach ($this->getFramePages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li class="current"><?php echo $_page ?></li>
                    <?php else: ?>
                        <li><a href="<?php echo($currentProductUrl . '?r_p=' . $this->getPageNumber($_page)); ?>" data-type="r-page" data-number="<?php echo $this->getPageNumber($_page); ?>"><?php echo $_page ?></a></li>
                    <?php endif;?>
                <?php endforeach;?>

                <?php if ($this->canShowNextJump()): ?>
                    <li><a class="next_jump" title="" href="<?php echo($currentProductUrl . '?r_p=' . $this->getNextJumpNumber()); ?>" data-type="r-page" data-number="<?php echo $this->getNextJumpNumber(); ?>">...</a></li>
                <?php endif;?>

                <?php if ($this->canShowLast()): ?>
                    <li><a class="last" href="<?php echo($currentProductUrl . '?r_p=' . $this->getLastPageNumber()); ?>" data-type="r-page" data-number="<?php echo $this->getLastPageNumber(); ?>"><?php echo $this->getLastPageNum() ?></a></li>
                <?php endif;?>

                <?php if (!$this->isLastPage()): ?>
                    <li>
                        <a class="next<?php if(!$this->getAnchorTextForNext()): ?> i-next<?php endif; ?>" href="<?php echo($currentProductUrl . '?r_p=' . $this->getNextPageNumber()); ?>" title="<?php echo $this->__('Next') ?>" data-type="r-page" data-number="<?php echo $this->getNextPageNumber(); ?>">
                            <?php if(!$this->getAnchorTextForNext()): ?>
                                <?php echo $this->__('Next') ?>
                            <?php else: ?>
                                <?php echo $this->getAnchorTextForNext() ?>
                            <?php endif;?>
                        </a>
                    </li>
                <?php endif;?>
            </ol>
        </div>
    <?php endif; ?>

    <?php if($this->getUseContainer()): ?>
        </div>
    <?php endif ?>

<?php endif ?>
